### ISSUE TITLE
 Issue with "bundle install --deployment"

### ISSUE THREAD

**Issue by firesalp** [openwisp/OpenWISP-Manager#33]
Hi,

I'm trying to install the OpenWISP infrastructure to try it out. I repeat all the install steps several times without any success. I'm running Debian 7 Wheezy, installed Ruby on Rails, Apache an Passenger successfully.

When I run "bundle install --deployment", some errors occurs:
- Like the issue #25, libarchive give an error. I commented this out and added libarchive-static instead. Then this message appears: _The message You are trying to install in deployment mode after changing
your Gemfile._
- Some other same errors are showing up..

Is there someone who can help me set this up correctly? Or is the code maybe broken?
Does someont did a complete __How__ To to do it the right way?

Thanks

**Comment by urako** [comment]
Hi Firesalp,

i also ran into Issues. My take is that maybe the environment requirements may be outdated.

like some parts need mysql 5.3 at least etc etc

I then got stuck and was unable to continue..
I guess the mainainers already have working Openwisp-managers to work from and do not need to recompile them again. They do not see the problems we are facing.

Maybe one of them can try if for a change. realy like the Openwisp initiative and would like to implement it as well.

**Comment by firesalp** [comment]
Hi Urako,

Glad to see that i'm not the only one stucking on the setup. I really appriciate the OpenWisp initiative too, but as is, it's very hard to understand how to install it correctly. Moreover, i'm not so familliar with Ruby on Rails..

I came out my second problem with linecache. In fact I was running Ruby 1.9.x, and some GEMs aren't  runnin on that version. So I had to install Ruby 1.8 from the Ruby Enterprise site, but I had some troubles with openSsl support to install passenger. 

I had luck with installing Ruby environment via RVM, and i'ts now running fine. I will try to build the OpenWISP-Manager soon. I will come back on this issue for updates.

Urako, on what system are you installing it? Maybe we can work together to get it work? And maybe make a complete HowTo procedure?

**Comment by firesalp** [comment]
After resolving the some problems (mysql2 gem, downgrades of gem system, ...), I edited the config/database.yml and created the database successfully. I copied the lunch script and BackgrounDRb is running fine (with some warnings for depreciated commands)

Everything seems running but I steel can't acces the WebUI. Apache is simply listing the directory. Some info about this?

**Comment by urako** [comment]
That will be great skype:andrejfx

**Comment by urako** [comment]
I battled with the following environment:

I ended up using rvm
mysql 5.5
ruby 1.9.3 ( Gem:InstallError: highline requires Ruby version >= 1.9.3 )

I ended up with a warning that SystemTimer using outdated syntex or something

which means all references in the files for SystemTimer needs to change to be compatible with my setup.

**Comment by firesalp** [comment]
Humm I didn't have something like this. 
One thing is shure, Ruby has to be 1.8.7 due to incompatible GEM's, 
Rake has to be at v 0.9.2 
and GEM system must be at v1.8.25

My MySQL version is the lastest Debian stable:
> root@TEST-OpenWISP:/opt/owm# mysql -V
> mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.2

**Comment by urako** [comment]
I guess the warnings might have been important then in your case.

What were they about?

**Comment by urako** [comment]
I am willing to try your setup i you documented how you got this far

**Comment by firesalp** [comment]
root@TEST-OpenWISP:/opt/owm# rake daemons:start
rake/rdoctask is deprecated.  Use rdoc/task instead (in RDoc 2.4.2+)
DEPRECATION WARNING: Rake tasks in vendor/plugins/backgroundrb/tasks and vendor/plugins/jrails/tasks are deprecated. Use lib/tasks instead. (called from /usr/local/rvm/gems/ruby-1.8.7-head/gems/rails-2.3.11/lib/tasks/rails.rb:10)
Starting BackgrounDRb...
NOTE: Gem.source_index is deprecated, use Specification. It will be removed on or after 2011-11-01.
Gem.source_index called from /usr/local/rvm/gems/ruby-1.8.7-head/gems/rails-2.3.11/lib/rails/gem_dependency.rb:21.
NOTE: Gem::SourceIndex#refresh! is deprecated with no replacement. It will be removed on or after 2011-11-01.
Gem::SourceIndex#refresh! called from /usr/local/rvm/gems/ruby-1.8.7-head/gems/rails-2.3.11/lib/rails/vendor_gem_source_index.rb:34.
NOTE: Gem::SourceIndex#load_gems_in is deprecated with no replacement. It will be removed on or after 2011-11-01.
Gem::SourceIndex#load_gems_in called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:322.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
BackgrounDRb: running...

**Comment by urako** [comment]
ruby 1.8.7 also to new then?

**Comment by firesalp** [comment]
Like they said:
> Even so, what we are currently using (and find quite stable) is the following enviroment:
> Ruby Enterprise Edition 1.8 (www.rubyenterpriseedition.com/index.html)
> Apache 2.2 (www.apache.org/)
> Phusion Passenger 2.2 (www.modrails.com/index.html)
> MySQL 5.1 (dev.mysql.com/downloads/mysql/)

I'm trying to reproduce my current install and I will post the steps here. Are you on Debian?

**Comment by urako** [comment]
what version of rails?

**Comment by firesalp** [comment]
> root@TEST-OpenWISP:/opt/owm# rails -v
> Rails 2.3.11

**Comment by urako** [comment]
if I check similar errors in google add_spec still worked in ruby1.8 1

**Comment by firesalp** [comment]
I have an error with 
> rvm install 1.8.1

**Comment by urako** [comment]
does 
ruby -v     
give you 1.8.7

**Comment by firesalp** [comment]
Yep..
> root@TEST-OpenWISP:/opt/owm# ruby -v
ruby 1.8.7 (2014-01-28 patchlevel 376) [x86_64-linux]

**Comment by urako** [comment]
cannot see where the switch happened maybe you should step up and see what is the lowest that can install and hope it works

**Comment by firesalp** [comment]
I tryied Ruby Enterprise, but passenger will not install due to missing OpenSSL lib (wich I installed)

**Comment by firesalp** [comment]
Warnings are gone when I start the app and seems to runn correctly (top). Do you maybe where I can find the web interface?

**Comment by firesalp** [comment]
What I dont understaind is that there are no index.html or so in the public dir...

**Comment by urako** [comment]
As far as n can gather they are going to be deployed by rails at var/www or var/rails by the owm-deamons.

But I am not very familiar with ruby to know for sure. there are index.html.rb in one of the app directories

**Comment by firesalp** [comment]
Oh, I cant downgrade to ruby 1.8.1, because bundler requires ruby 1.8.7.

**Comment by urako** [comment]
catch 22 I see

**Comment by urako** [comment]
earlier version of bundler?

**Comment by firesalp** [comment]
Now I have this error:
> root@TEST-OpenWISP:/opt/owm# service owm-daemons start
[....] Starting OpenWISP daemon:/usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems.rb:900:in `report_activate_error': Could not find RubyGem bundler (>= 0) (Gem::LoadError)
        from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems.rb:248:in `activate'
        from /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems.rb:1276:in `gem'
        from /usr/local/rvm/gems/ruby-1.8.7-head/bin/bundle:18
 failed!

I cant figure out what the problem is.. I reinstalled bundler, remove it, try different versions... nothing to do. By the way, when bundler in completly uninstalled, the message in different:
> root@TEST-OpenWISP:/opt/owm# service owm-daemons start
[....] Starting OpenWISP daemon:/etc/init.d/owm-daemons: 36: /etc/init.d/owm-daemons: bundle: not found
 failed!

Any help will be apreciated :)

**Comment by urako** [comment]
Also stuck Here.

We need Help!

**Comment by reinerotto** [comment]
I like the general appoach, but the setup/installation is a mess. Also for me, as I am not familar with ruby, too. Giving up on trying this stuff, as these installation issues will prohibit widespread use.

**Comment by yurik94** [comment]
Same problem here, can't get it working....
We really need help.
